theme = "github_light"

[editor]
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = false

[editor.whitespace]
render = "all"
space = "."

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
